apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-deposit
  labels:
    app: service-deposit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-deposit
  template:
    metadata:
      labels:
        app: service-deposit
    spec:
      containers:
      - name: app-deposit
        image: jeanflores2c93/aforo255-nodejs-deposit:1
        ports:
        - containerPort: 5003
        env:
        - name: NACOS_SERVERADDR
          value: "161.35.233.217:8848"
        - name: NACOS_NAMESPACE
          value: "aforo255"
        - name: NACOS_IDENTITYKEY
          value: "nacos"
        - name: NACOS_IDENTITYVALUE
          value: "nacos"
        - name: NACOS_ENV
          value: "PROD"
